version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - "27020:27017"
  frond:
    build: ./frond/
    ports:
      - "4200:4200"
    environment:
      portBACK: "192.168.99.100:2120"
      
  back:
    build: ./back/
    ports:
      - "2120:2100"
    environment:
      portDB: 27020
    links:
      - "db:DB"
    depends_on:
      - db
      - frond
